
const INCREAMENT = "INCREAMENT"
const SUBTRACT = "SUBTRACT"
const CHANGE_BOARDLIST = 'CHANGE_BOARDLIST'
const CHANGE_HOMELIST = 'CHANGE_HOMELIST'

export {
	INCREAMENT,
	SUBTRACT,
	CHANGE_BOARDLIST,
	CHANGE_HOMELIST
}
