const ADD_NEW_TODO = 'ADD_NEW_TODO'
const REMOVE_TODO = 'REMOVE_TODO'
const CHANGE_USERNAME = 'CHANGE_USERNAME'
const EXIT = 'EXIT'

export {
	ADD_NEW_TODO,
	REMOVE_TODO,
	CHANGE_USERNAME,
	EXIT
}
